name: Cross-Platform Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: windows
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build --outdir dist/${{ matrix.platform }}
    
    - name: Check package
      run: |
        twine check dist/${{ matrix.platform }}/*
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: agently-cli-${{ matrix.platform }}-${{ matrix.arch }}
        path: dist/${{ matrix.platform }}/*
        retention-days: 5

  # Only run this job on GitHub Releases
  publish:
    name: Publish to PyPI
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        # Combine all platform-specific builds into a single directory
        mkdir -p dist/combined
        find dist -type f -name "*.whl" -exec cp {} dist/combined/ \;
        find dist -type f -name "*.tar.gz" -exec cp {} dist/combined/ \;
        
        # Publish to PyPI
        twine check dist/combined/*
        twine upload dist/combined/* 